### ISSUE TITLE
Octo sound card out of stock

### ISSUE THREAD

**Issue by gdragoi14** [Audio-Injector/Octo#4]
Hi,

I am interested in buying the octo sound card but it seems to be out of stock on both the audio injector website and amazon. Is there a timeline for when it will be back in stock?

Cheers,
George

**Comment by flatmax** [comment]
Hi, thanks for the interest.

We expect to be able to ship again within a few months. We are changing 
the way we source FPGA chips and this is the current slow down. Apologies.

**Comment by gdragoi14** [comment]
Great! Looking forward to it
